language: node_js
sudo: required
notifications:
  email: false
node_js:
  - '10'
before_install:
  - export CHROME_BIN=chromium-browser
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
after_success:
  - npm run build
  - cp .git dist/@ngx-translate/http-loader/ -r # required by semantic release
  - cp README.md dist/@ngx-translate/http-loader/
  - cd dist/@ngx-translate/http-loader/
  - npm install
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
